import { Chain, Step } from '@ephox/agar';
import { Element } from '@ephox/sugar';
declare const _default: {
    cSetSourceInput: (ui: any, value: any) => Chain<any, any>;
    cFindTextare: (ui: any, text: any) => Chain<any, any>;
    cFakeEvent: (name: any) => Chain<Element, Element>;
    cFindInDialog: (mapper: any) => (ui: any, text: any) => Chain<any, any>;
    sOpenDialog: (ui: any) => Step<any, any>;
    sCloseDialog: (ui: any) => any;
    sSubmitDialog: (ui: any) => any;
    sTestEmbedContentFromUrl: (ui: any, url: any, content: any) => Step<any, any>;
    sSetFormItemNoEvent: (ui: any, value: any) => Step<{}, {}>;
    sAssertEditorContent: (apis: any, editor: any, expected: any) => Step<{}, {}>;
    sSetSetting: (editorSetting: any, key: any, value: any) => Step<{}, {}>;
    sSubmitAndReopen: (ui: any) => Step<any, any>;
    sAssertWidthValue: (ui: any, value: any) => Step<{}, {}>;
    sAssertHeightValue: (ui: any, value: any) => Step<{}, {}>;
    sPasteSourceValue: (ui: any, value: any) => Step<{}, {}>;
    sAssertSizeRecalcConstrained: (ui: any) => Step<any, any>;
    sAssertSizeRecalcConstrainedReopen: (ui: any) => Step<any, any>;
    sAssertSizeRecalcUnconstrained: (ui: any) => Step<any, any>;
    sAssertEmbedContent: (ui: any, content: any) => Step<{}, {}>;
    sAssertSourceValue: (ui: any, value: any) => Step<{}, {}>;
    sChangeWidthValue: (ui: any, value: any) => Step<{}, {}>;
    sPasteTextareaValue: (ui: any, value: any) => Step<{}, {}>;
};
export default _default;
